import Head from "next/head";
import Layout from "../components/layout";
import styles from "../styles/Home.module.css";

export default function About() {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Onur - About</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <p className={styles.title}>About</p>
      </div>
    </Layout>
  );
}
