import Head from "next/head";
import Layout from "../components/layout";
import Card from "../components/card";
import styles from "../styles/Home.module.css";
import { fetchEntries } from "./api/post";

export default function Blog({ posts }) {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Onur - Blog</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <p className={styles.title}>Blog</p>
        <div className={styles.cards}>
          {posts.map((p) => {
            return (
              posts && (
                <Card
                  key={p.sys.id}
                  date={p.fields.date}
                  image={p.fields.image.fields}
                  title={p.fields.title}
                  description={p.fields.description}
                  id={p.sys.id}
                />
              )
            );
          })}
        </div>
      </div>
    </Layout>
  );
}

export async function getStaticProps() {
  const res = await fetchEntries();
  const posts = await res.map((p) => {
    return p;
  });

  return {
    props: {
      posts,
    },
  };
}
