import Head from "next/head";
import Layout from "../components/layout";
import Card from "../components/card";
import styles from "../styles/Home.module.css";
import { fetchEntries, fetchTags } from "./api/post";

export default function Blog({ posts, tags }) {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Onur - Blog</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <p className={styles.title}>Blog</p>
        <div className={styles.tags}>
          {tags &&
            tags.items.map((tag) => {
              return (
                <div key={tag.name} className={styles.tag}>
                  {tag.name}
                </div>
              );
            })}
        </div>
        <div className={styles.cards}>
          {posts.map((post) => {
            return (
              posts && (
                <Card
                  key={post.sys.id}
                  date={post.fields.date}
                  image={post.fields.image.fields}
                  title={post.fields.title}
                  description={post.fields.description}
                  id={post.sys.id}
                  metaTags={post.metadata.tags}
                />
              )
            );
          })}
        </div>
      </div>
    </Layout>
  );
}

export async function getStaticProps() {
  const posts = await fetchEntries();
  const tags = await fetchTags();
  return {
    props: {
      posts,
      tags,
    },
  };
}
