import Head from "next/head";
import Layout from "../components/layout";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Onur - Home</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <p className={styles.title}>Hi, I'm Onur Karaoğlan</p>
        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <p className={styles.title}>Hi, I'm Onur Karaoğlan</p>
        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <p className={styles.title}>Hi, I'm Onur Karaoğlan</p>
        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <p className={styles.title}>Hi, I'm Onur Karaoğlan</p>
        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <p className={styles.title}>Hi, I'm Onur Karaoğlan</p>
        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <p className={styles.title}>Hi, I'm Onur Karaoğlan</p>
        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <p className={styles.title}>Hi, I'm Onur Karaoğlan</p>
        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <p className={styles.title}>Hi, I'm Onur Karaoğlan</p>
        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <p className={styles.title}>Hi, I'm Onur Karaoğlan</p>
        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <p className={styles.title}>Hi, I'm Onur Karaoğlan</p>
        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <p className={styles.title}>Hi, I'm Onur Karaoğlan</p>
        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>
      </div>
    </Layout>
  );
}
