import Head from "next/head";
import Layout from "../components/layout";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Onur - Home</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <p className={styles.title}>Hi, I am Onur Karaoğlan</p>
        <p className={styles.content}>
          I'm Onur Karaoğlan, a Full Stack Engineer from Istanbul, Turkey. I
          love to learn and discover new things about Web Development. You can
          catch my code snippets on Twitter and Linkedin.{" "}
          <Link href="/about">
            <a>Click here</a>
          </Link>{" "}
          to learn more about me.
        </p>
      </div>
    </Layout>
  );
}
